<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <xs:element name="installation">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="type" type="xs:string"/>
        <xs:element name="city" type="xs:string"/>
        <xs:element name="sports" minOccurs="0">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="sportId" type="xs:string"/>
              <xs:element name="name" type="xs:string"/>
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <xs:element name="location" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="type" type="xs:string"/>
              <xs:element name="coordinates" type="xs:decimal" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="externalId" type="xs:string" minOccurs="0" nillable="true"/>
        <xs:element name="source" type="xs:string" minOccurs="0"/>
        <xs:element name="lastUpdated" type="xs:string" minOccurs="0"/>
        <xs:element name="createdAt" type="xs:string" minOccurs="0"/>
        <xs:element name="updatedAt" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
